### ISSUE TITLE
[Issue]: ./amd-smi event can't be stopped/killed

### ISSUE THREAD

**Issue by Ori-Messinger** [RadeonOpenCompute/amdsmi#24]
### Problem Description

When running ./amd-smi event it doesn't stop when you hit "q + ENTER" or "Ctrl + c" however ./rocm-smi --showevents does.

### Operating System

Ubuntu 22.04

### CPU

EYPC 7251

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.1.0

**Comment by dmitrii-galantsev** [comment]
Yup was able to repro

**Comment by harkgill-amd** [comment]
Hi @Ori-Messinger, the following patch has been merged to resolve the failure to exit amd-smi event, https://github.com/ROCm/amdsmi/commit/d263b53797db492f9d6305e334fa7b9788dc5cc9. 

Could you please build amd-smi from the `amd-staging` branch and confirm if the patch addresses the issue on your end?
