### ISSUE TITLE
[Issue]: amd_hsmp.h local copy of kernel header

### ISSUE THREAD

**Issue by trixirt** [RadeonOpenCompute/amdsmi#47]
### Problem Description

amd_hsmp.h is fetched as part of the build process from the upstream kernel here
 https://github.com/ROCm/amdsmi/blob/amd-staging/CMakeLists.txt#L125 it should come from the system's kernel header.  A mismatch could crash the app or the kernel.

### Operating System

Fedora Rawhide

### CPU

x86_64

### GPU

AMD Radeon Pro W7900

### ROCm Version

ROCm 6.2.0

**Comment by harkgill-amd** [comment]
Closing this issue as related PR has been merged.
